-- =====================================================================
-- LinkAI: modelo de acessos internos (empresa / obra / perfil / permissão)
-- =====================================================================

-- ---------------------------------------------------------------- empresas
ALTER TABLE public.empresas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- ---------------------------------------------------------------- usuarios
ALTER TABLE public.usuarios
  ADD COLUMN IF NOT EXISTS is_platform_superadmin boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS two_factor_policy text NOT NULL DEFAULT 'optional';

DO $$ BEGIN
  ALTER TABLE public.usuarios
    ADD CONSTRAINT usuarios_two_factor_policy_check
    CHECK (two_factor_policy IN ('required','optional','disabled'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ------------------------------------------------------- perfis internos
CREATE TABLE IF NOT EXISTS public.linkai_perfis_internos (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  descricao text,
  escopo text NOT NULL CHECK (escopo IN ('plataforma','empresa','obra')),
  nivel integer NOT NULL DEFAULT 0,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.linkai_permissoes (
  codigo text PRIMARY KEY,
  nome text NOT NULL,
  descricao text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.linkai_perfil_permissoes (
  perfil_codigo text NOT NULL REFERENCES public.linkai_perfis_internos(codigo) ON DELETE CASCADE,
  permissao_codigo text NOT NULL REFERENCES public.linkai_permissoes(codigo) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (perfil_codigo, permissao_codigo)
);

-- ----------------------------------------------------------------- obras
CREATE TABLE IF NOT EXISTS public.linkai_obras (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  empresa_id integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  codigo text NOT NULL,
  nome text NOT NULL,
  tipo text NOT NULL DEFAULT 'obra' CHECK (tipo IN ('escritorio','obra')),
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS linkai_obras_codigo_empresa_uniq
  ON public.linkai_obras (empresa_id, upper(codigo));
CREATE UNIQUE INDEX IF NOT EXISTS linkai_obras_um_escritorio_ativo
  ON public.linkai_obras (empresa_id) WHERE tipo = 'escritorio' AND ativo;
CREATE INDEX IF NOT EXISTS linkai_obras_empresa_idx ON public.linkai_obras (empresa_id);

-- ------------------------------------------------------ usuario x obras
CREATE TABLE IF NOT EXISTS public.linkai_usuario_obras (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id integer NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
  obra_id uuid NOT NULL REFERENCES public.linkai_obras(id) ON DELETE CASCADE,
  perfil_codigo text NOT NULL REFERENCES public.linkai_perfis_internos(codigo),
  principal boolean NOT NULL DEFAULT false,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS linkai_usuario_obras_ativa_uniq
  ON public.linkai_usuario_obras (usuario_id, obra_id) WHERE ativo;
CREATE UNIQUE INDEX IF NOT EXISTS linkai_usuario_obras_uma_principal
  ON public.linkai_usuario_obras (usuario_id) WHERE principal AND ativo;
CREATE INDEX IF NOT EXISTS linkai_usuario_obras_obra_idx ON public.linkai_usuario_obras (obra_id);

-- -------------------------------------------------------------- convites
CREATE TABLE IF NOT EXISTS public.linkai_user_convites (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nome text NOT NULL,
  email text NOT NULL,
  empresa_id integer NOT NULL REFERENCES public.empresas(id) ON DELETE CASCADE,
  obra_id uuid REFERENCES public.linkai_obras(id) ON DELETE SET NULL,
  perfil_codigo text NOT NULL REFERENCES public.linkai_perfis_internos(codigo),
  two_factor_policy text NOT NULL DEFAULT 'optional'
    CHECK (two_factor_policy IN ('required','optional','disabled')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','linked','canceled')),
  criado_por uuid,
  criado_em timestamptz NOT NULL DEFAULT now(),
  vinculado_em timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS linkai_user_convites_pending_email
  ON public.linkai_user_convites (lower(email)) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS linkai_user_convites_empresa_idx
  ON public.linkai_user_convites (empresa_id);

-- --------------------------------------------------------- activity logs
CREATE TABLE IF NOT EXISTS public.linkai_activity_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_user_id uuid,
  actor_usuario_id integer REFERENCES public.usuarios(id) ON DELETE SET NULL,
  empresa_id integer REFERENCES public.empresas(id) ON DELETE SET NULL,
  obra_id uuid REFERENCES public.linkai_obras(id) ON DELETE SET NULL,
  action text NOT NULL,
  status text NOT NULL DEFAULT 'started' CHECK (status IN ('started','succeeded','failed','canceled','info')),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  finished_at timestamptz
);

CREATE INDEX IF NOT EXISTS linkai_activity_logs_actor_idx ON public.linkai_activity_logs (actor_usuario_id, created_at DESC);
CREATE INDEX IF NOT EXISTS linkai_activity_logs_obra_idx ON public.linkai_activity_logs (obra_id, created_at DESC);
CREATE INDEX IF NOT EXISTS linkai_activity_logs_empresa_idx ON public.linkai_activity_logs (empresa_id, created_at DESC);

-- ----------------------------------------------- updated_at nas novas tabelas
DROP TRIGGER IF EXISTS linkai_perfis_internos_updated_at ON public.linkai_perfis_internos;
CREATE TRIGGER linkai_perfis_internos_updated_at BEFORE UPDATE ON public.linkai_perfis_internos
  FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
DROP TRIGGER IF EXISTS linkai_obras_updated_at ON public.linkai_obras;
CREATE TRIGGER linkai_obras_updated_at BEFORE UPDATE ON public.linkai_obras
  FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
DROP TRIGGER IF EXISTS linkai_usuario_obras_updated_at ON public.linkai_usuario_obras;
CREATE TRIGGER linkai_usuario_obras_updated_at BEFORE UPDATE ON public.linkai_usuario_obras
  FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();
DROP TRIGGER IF EXISTS linkai_user_convites_updated_at ON public.linkai_user_convites;
CREATE TRIGGER linkai_user_convites_updated_at BEFORE UPDATE ON public.linkai_user_convites
  FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();

-- ===================================================== catálogo de perfis
INSERT INTO public.linkai_perfis_internos (codigo, nome, descricao, escopo, nivel) VALUES
  ('superadmin_2lock','Superadmin 2LOCK','Acesso total à plataforma; exclusivo da 2LOCK.','plataforma',100),
  ('supervisor_empresa','Supervisor da empresa','Administra usuários, funções e obras da própria empresa.','empresa',80),
  ('gestor_obra','Gestor de obra','Gestão operacional completa da obra atribuída.','obra',60),
  ('fiscal_obra','Fiscal de obra','Processa documentos e lança notas da obra atribuída.','obra',50),
  ('financeiro_obra','Financeiro da obra','Lançamentos e consultas financeiras da obra.','obra',50),
  ('compras_obra','Compras da obra','Documentos e cadastros de compras da obra.','obra',50),
  ('consulta_obra','Consulta da obra','Somente leitura da obra atribuída.','obra',10)
ON CONFLICT (codigo) DO UPDATE
  SET nome = EXCLUDED.nome, descricao = EXCLUDED.descricao,
      escopo = EXCLUDED.escopo, nivel = EXCLUDED.nivel, ativo = true;

INSERT INTO public.linkai_permissoes (codigo, nome) VALUES
  ('home.view','Acessar início'),
  ('documents.process','Processar documentos'),
  ('notes.launch','Lançar notas'),
  ('ai.use','Usar IA'),
  ('spreadsheets.view','Ver planilhas'),
  ('cloud.view','Ver nuvem'),
  ('files.view','Ver arquivos'),
  ('history.view','Ver histórico'),
  ('logs.view','Ver logs'),
  ('queue.monitor','Monitorar fila'),
  ('access.manage','Administrar acessos'),
  ('works.manage','Administrar obras'),
  ('records.manage','Administrar cadastros')
ON CONFLICT (codigo) DO UPDATE SET nome = EXCLUDED.nome;

-- matriz de permissões
DELETE FROM public.linkai_perfil_permissoes;

INSERT INTO public.linkai_perfil_permissoes (perfil_codigo, permissao_codigo)
SELECT 'superadmin_2lock', codigo FROM public.linkai_permissoes;

INSERT INTO public.linkai_perfil_permissoes (perfil_codigo, permissao_codigo)
SELECT 'supervisor_empresa', codigo FROM public.linkai_permissoes;

INSERT INTO public.linkai_perfil_permissoes (perfil_codigo, permissao_codigo)
SELECT 'gestor_obra', c FROM unnest(ARRAY['home.view','documents.process','notes.launch','ai.use',
  'spreadsheets.view','cloud.view','files.view','history.view','logs.view','queue.monitor','records.manage']) c;

INSERT INTO public.linkai_perfil_permissoes (perfil_codigo, permissao_codigo)
SELECT 'fiscal_obra', c FROM unnest(ARRAY['home.view','documents.process','notes.launch','ai.use',
  'spreadsheets.view','files.view','history.view']) c;

INSERT INTO public.linkai_perfil_permissoes (perfil_codigo, permissao_codigo)
SELECT 'financeiro_obra', c FROM unnest(ARRAY['home.view','notes.launch','spreadsheets.view',
  'files.view','history.view','records.manage']) c;

INSERT INTO public.linkai_perfil_permissoes (perfil_codigo, permissao_codigo)
SELECT 'compras_obra', c FROM unnest(ARRAY['home.view','documents.process','spreadsheets.view',
  'files.view','history.view','records.manage']) c;

INSERT INTO public.linkai_perfil_permissoes (perfil_codigo, permissao_codigo)
SELECT 'consulta_obra', c FROM unnest(ARRAY['home.view','spreadsheets.view','files.view','history.view']) c;

-- ============================================== ESCRITORIO automático
CREATE OR REPLACE FUNCTION public.linkai_ensure_escritorio(p_empresa_id integer)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE v_id uuid;
BEGIN
  SELECT id INTO v_id FROM public.linkai_obras
   WHERE empresa_id = p_empresa_id AND tipo = 'escritorio' AND ativo LIMIT 1;
  IF v_id IS NOT NULL THEN RETURN v_id; END IF;

  INSERT INTO public.linkai_obras (empresa_id, codigo, nome, tipo, ativo)
  VALUES (p_empresa_id, 'ESCRITORIO', 'ESCRITORIO', 'escritorio', true)
  ON CONFLICT (empresa_id, upper(codigo))
  DO UPDATE SET ativo = true, tipo = 'escritorio'
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.linkai_empresa_escritorio_trigger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  PERFORM public.linkai_ensure_escritorio(NEW.id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS linkai_empresas_escritorio ON public.empresas;
CREATE TRIGGER linkai_empresas_escritorio AFTER INSERT ON public.empresas
  FOR EACH ROW EXECUTE FUNCTION public.linkai_empresa_escritorio_trigger();

-- ==================================================== helpers de contexto
CREATE OR REPLACE FUNCTION public.linkai_current_usuario()
RETURNS public.usuarios
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$ SELECT u.* FROM public.usuarios u WHERE u.auth_user_id = auth.uid() LIMIT 1 $$;

CREATE OR REPLACE FUNCTION public.linkai_current_usuario_id()
RETURNS integer
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$ SELECT u.id FROM public.usuarios u WHERE u.auth_user_id = auth.uid() AND u.ativo LIMIT 1 $$;

CREATE OR REPLACE FUNCTION public.linkai_current_empresa_id()
RETURNS integer
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$ SELECT u.empresa_id FROM public.usuarios u WHERE u.auth_user_id = auth.uid() AND u.ativo LIMIT 1 $$;

CREATE OR REPLACE FUNCTION public.linkai_is_platform_superadmin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT COALESCE((SELECT u.is_platform_superadmin AND u.ativo FROM public.usuarios u
                    WHERE u.auth_user_id = auth.uid() LIMIT 1), false)
$$;

CREATE OR REPLACE FUNCTION public.linkai_perfil_principal(p_usuario_id integer DEFAULT NULL)
RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  WITH alvo AS (
    SELECT COALESCE(p_usuario_id,
      (SELECT u.id FROM public.usuarios u WHERE u.auth_user_id = auth.uid() LIMIT 1)) AS id
  )
  SELECT CASE
    WHEN (SELECT COALESCE(u.is_platform_superadmin, false) FROM public.usuarios u, alvo
           WHERE u.id = alvo.id) THEN 'superadmin_2lock'
    ELSE COALESCE((
      SELECT uo.perfil_codigo FROM public.linkai_usuario_obras uo, alvo
       WHERE uo.usuario_id = alvo.id AND uo.ativo
       ORDER BY uo.principal DESC, uo.created_at
       LIMIT 1), 'sem_acesso')
  END
$$;

CREATE OR REPLACE FUNCTION public.linkai_is_supervisor()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.linkai_usuario_obras uo
      JOIN public.usuarios u ON u.id = uo.usuario_id
     WHERE u.auth_user_id = auth.uid() AND u.ativo AND uo.ativo
       AND uo.perfil_codigo = 'supervisor_empresa'
  )
$$;

CREATE OR REPLACE FUNCTION public.linkai_has_permissao(_permissao text)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT public.linkai_is_platform_superadmin() OR EXISTS (
    SELECT 1 FROM public.linkai_usuario_obras uo
      JOIN public.usuarios u ON u.id = uo.usuario_id
      JOIN public.linkai_perfil_permissoes pp ON pp.perfil_codigo = uo.perfil_codigo
     WHERE u.auth_user_id = auth.uid() AND u.ativo AND uo.ativo
       AND pp.permissao_codigo = _permissao
  )
$$;

-- obras visíveis ao usuário corrente
CREATE OR REPLACE FUNCTION public.linkai_obras_visiveis()
RETURNS SETOF uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT o.id FROM public.linkai_obras o
   WHERE public.linkai_is_platform_superadmin()
      OR (public.linkai_is_supervisor() AND o.empresa_id = public.linkai_current_empresa_id())
      OR EXISTS (
        SELECT 1 FROM public.linkai_usuario_obras uo
          JOIN public.usuarios u ON u.id = uo.usuario_id
         WHERE uo.obra_id = o.id AND uo.ativo AND u.ativo AND u.auth_user_id = auth.uid())
$$;

CREATE OR REPLACE FUNCTION public.linkai_can_access_obra(p_obra_id uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT p_obra_id IS NOT NULL
     AND p_obra_id IN (SELECT public.linkai_obras_visiveis())
$$;

CREATE OR REPLACE FUNCTION public.linkai_can_manage_empresa(p_empresa_id integer)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT public.linkai_is_platform_superadmin()
      OR (public.linkai_has_permissao('access.manage')
          AND p_empresa_id IS NOT NULL
          AND p_empresa_id = public.linkai_current_empresa_id())
$$;

CREATE OR REPLACE FUNCTION public.linkai_obra_principal(p_usuario_id integer DEFAULT NULL)
RETURNS uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
  WITH alvo AS (
    SELECT COALESCE(p_usuario_id,
      (SELECT u.id FROM public.usuarios u WHERE u.auth_user_id = auth.uid() LIMIT 1)) AS id
  )
  SELECT uo.obra_id FROM public.linkai_usuario_obras uo, alvo
   WHERE uo.usuario_id = alvo.id AND uo.ativo
   ORDER BY uo.principal DESC, uo.created_at LIMIT 1
$$;

-- ======================================== atribuição atômica de usuário
CREATE OR REPLACE FUNCTION public.linkai_assign_user_to_obra(
  p_usuario_id integer,
  p_obra_id uuid,
  p_perfil_codigo text,
  p_principal boolean DEFAULT false
)
RETURNS public.linkai_usuario_obras
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_usuario public.usuarios;
  v_obra public.linkai_obras;
  v_perfil public.linkai_perfis_internos;
  v_row public.linkai_usuario_obras;
  v_is_service boolean := (current_setting('request.jwt.claims', true) IS NULL);
BEGIN
  SELECT * INTO v_usuario FROM public.usuarios WHERE id = p_usuario_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Usuário não encontrado.' USING ERRCODE = '22023'; END IF;
  IF NOT COALESCE(v_usuario.ativo, false) THEN
    RAISE EXCEPTION 'Usuário inativo.' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_obra FROM public.linkai_obras WHERE id = p_obra_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Obra não encontrada.' USING ERRCODE = '22023'; END IF;
  IF NOT v_obra.ativo THEN RAISE EXCEPTION 'Obra inativa.' USING ERRCODE = '22023'; END IF;

  SELECT * INTO v_perfil FROM public.linkai_perfis_internos WHERE codigo = p_perfil_codigo AND ativo;
  IF NOT FOUND THEN RAISE EXCEPTION 'Perfil interno inválido: %', p_perfil_codigo USING ERRCODE = '22023'; END IF;

  IF p_perfil_codigo = 'superadmin_2lock' THEN
    RAISE EXCEPTION 'O perfil superadmin_2lock é de plataforma e não pode ser atribuído a uma obra.'
      USING ERRCODE = '22023';
  END IF;

  IF p_perfil_codigo = 'supervisor_empresa' AND v_obra.tipo <> 'escritorio' THEN
    RAISE EXCEPTION 'supervisor_empresa só pode ser atribuído ao ESCRITORIO da empresa.'
      USING ERRCODE = '22023';
  END IF;

  IF v_usuario.empresa_id IS NULL OR v_usuario.empresa_id <> v_obra.empresa_id THEN
    RAISE EXCEPTION 'Usuário e obra pertencem a empresas diferentes.' USING ERRCODE = '22023';
  END IF;

  -- Autorização: service_role (sem JWT) passa direto; caso contrário exige poder
  -- administrar a empresa da obra.
  IF NOT v_is_service AND auth.uid() IS NOT NULL THEN
    IF NOT public.linkai_can_manage_empresa(v_obra.empresa_id) THEN
      RAISE EXCEPTION 'Permissão insuficiente para administrar acessos desta empresa.'
        USING ERRCODE = '42501';
    END IF;
  END IF;

  -- Serializa por usuário e desativa a principal anterior na mesma transação.
  PERFORM pg_advisory_xact_lock(hashtextextended('linkai_assign'::text, p_usuario_id));

  IF p_principal THEN
    UPDATE public.linkai_usuario_obras
       SET principal = false
     WHERE usuario_id = p_usuario_id AND principal AND ativo AND obra_id <> p_obra_id;
  END IF;

  INSERT INTO public.linkai_usuario_obras (usuario_id, obra_id, perfil_codigo, principal, ativo)
  VALUES (p_usuario_id, p_obra_id, p_perfil_codigo, COALESCE(p_principal, false), true)
  ON CONFLICT (usuario_id, obra_id) WHERE ativo
  DO UPDATE SET perfil_codigo = EXCLUDED.perfil_codigo,
                principal = EXCLUDED.principal,
                ativo = true,
                updated_at = now()
  RETURNING * INTO v_row;

  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.linkai_assign_user_to_obra(integer, uuid, text, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.linkai_assign_user_to_obra(integer, uuid, text, boolean)
  TO authenticated, service_role;

-- criação de obra comum
CREATE OR REPLACE FUNCTION public.linkai_create_obra(
  p_empresa_id integer, p_codigo text, p_nome text, p_tipo text DEFAULT 'obra'
)
RETURNS public.linkai_obras
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE v_row public.linkai_obras;
BEGIN
  IF auth.uid() IS NOT NULL AND NOT (
      public.linkai_is_platform_superadmin()
      OR (public.linkai_has_permissao('works.manage')
          AND p_empresa_id = public.linkai_current_empresa_id())) THEN
    RAISE EXCEPTION 'Permissão insuficiente para criar obras nesta empresa.' USING ERRCODE = '42501';
  END IF;

  IF COALESCE(p_tipo,'obra') NOT IN ('obra','escritorio') THEN
    RAISE EXCEPTION 'Tipo de obra inválido: %', p_tipo USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.linkai_obras (empresa_id, codigo, nome, tipo)
  VALUES (p_empresa_id, upper(trim(p_codigo)), p_nome, COALESCE(p_tipo,'obra'))
  RETURNING * INTO v_row;
  RETURN v_row;
END;
$$;

REVOKE ALL ON FUNCTION public.linkai_create_obra(integer, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.linkai_create_obra(integer, text, text, text) TO authenticated, service_role;

-- vínculo de convite no primeiro acesso
CREATE OR REPLACE FUNCTION public.linkai_link_convite(p_email text)
RETURNS public.linkai_user_convites
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  v_convite public.linkai_user_convites;
  v_usuario public.usuarios;
  v_obra uuid;
BEGIN
  SELECT * INTO v_convite FROM public.linkai_user_convites
   WHERE lower(email) = lower(p_email) AND status = 'pending' FOR UPDATE;
  IF NOT FOUND THEN RETURN NULL; END IF;

  SELECT * INTO v_usuario FROM public.usuarios WHERE lower(email) = lower(p_email) FOR UPDATE;
  IF NOT FOUND THEN RETURN NULL; END IF;

  UPDATE public.usuarios
     SET empresa_id = v_convite.empresa_id,
         two_factor_policy = v_convite.two_factor_policy,
         atualizado_em = now()
   WHERE id = v_usuario.id;

  v_obra := COALESCE(v_convite.obra_id, public.linkai_ensure_escritorio(v_convite.empresa_id));

  IF v_convite.perfil_codigo <> 'superadmin_2lock' THEN
    PERFORM public.linkai_assign_user_to_obra(v_usuario.id, v_obra, v_convite.perfil_codigo, true);
  END IF;

  UPDATE public.linkai_user_convites
     SET status = 'linked', vinculado_em = now()
   WHERE id = v_convite.id
  RETURNING * INTO v_convite;

  RETURN v_convite;
END;
$$;

REVOKE ALL ON FUNCTION public.linkai_link_convite(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.linkai_link_convite(text) TO service_role;

-- registro de atividade (somente metadados)
CREATE OR REPLACE FUNCTION public.linkai_log_activity(
  p_action text,
  p_status text DEFAULT 'info',
  p_payload jsonb DEFAULT '{}'::jsonb,
  p_message text DEFAULT NULL,
  p_obra_id uuid DEFAULT NULL,
  p_started_at timestamptz DEFAULT NULL,
  p_finished_at timestamptz DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  v_usuario public.usuarios;
  v_obra uuid;
  v_id uuid;
BEGIN
  SELECT * INTO v_usuario FROM public.usuarios WHERE auth_user_id = auth.uid() LIMIT 1;
  v_obra := COALESCE(p_obra_id, public.linkai_obra_principal(v_usuario.id));

  INSERT INTO public.linkai_activity_logs (
    actor_user_id, actor_usuario_id, empresa_id, obra_id, action, status,
    payload, message, started_at, finished_at
  ) VALUES (
    auth.uid(), v_usuario.id, v_usuario.empresa_id, v_obra, p_action,
    COALESCE(p_status,'info'),
    COALESCE(p_payload,'{}'::jsonb) - 'content' - 'contentBase64' - 'file' - 'bytes',
    p_message, COALESCE(p_started_at, now()), p_finished_at
  ) RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.linkai_log_activity(text, text, jsonb, text, uuid, timestamptz, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.linkai_log_activity(text, text, jsonb, text, uuid, timestamptz, timestamptz)
  TO authenticated, service_role;

-- ================================================ escopo de obra nas tabelas
ALTER TABLE public.pedidos_pendentes
  ADD COLUMN IF NOT EXISTS obra_id uuid REFERENCES public.linkai_obras(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS empresa_id integer REFERENCES public.empresas(id) ON DELETE SET NULL;
ALTER TABLE public.notas_processadas
  ADD COLUMN IF NOT EXISTS obra_id uuid REFERENCES public.linkai_obras(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS empresa_id integer REFERENCES public.empresas(id) ON DELETE SET NULL;
ALTER TABLE public.robot_logs
  ADD COLUMN IF NOT EXISTS obra_id uuid REFERENCES public.linkai_obras(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS empresa_id integer REFERENCES public.empresas(id) ON DELETE SET NULL;
ALTER TABLE public.lumina_queue_requests
  ADD COLUMN IF NOT EXISTS obra_id uuid REFERENCES public.linkai_obras(id) ON DELETE SET NULL;
ALTER TABLE public.lumina_jobs
  ADD COLUMN IF NOT EXISTS obra_id uuid REFERENCES public.linkai_obras(id) ON DELETE SET NULL;
ALTER TABLE public.lumina_queue_logs
  ADD COLUMN IF NOT EXISTS obra_id uuid REFERENCES public.linkai_obras(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS pedidos_pendentes_obra_idx ON public.pedidos_pendentes (obra_id);
CREATE INDEX IF NOT EXISTS notas_processadas_obra_idx ON public.notas_processadas (obra_id);
CREATE INDEX IF NOT EXISTS robot_logs_obra_idx ON public.robot_logs (obra_id);
CREATE INDEX IF NOT EXISTS lumina_queue_requests_obra_idx ON public.lumina_queue_requests (obra_id);
CREATE INDEX IF NOT EXISTS lumina_jobs_obra_idx ON public.lumina_jobs (obra_id);
CREATE INDEX IF NOT EXISTS lumina_queue_logs_obra_idx ON public.lumina_queue_logs (obra_id);

-- ====================================================== dados existentes
-- Empresas base (id explícito porque a coluna não era identity até agora)
INSERT INTO public.empresas (id, nome_fantasia, razao_social)
VALUES (1, '2LOCK', '2LOCK Tecnologia'), (2, 'Linka Engenharia', 'Linka Engenharia')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('public.empresas','id'),
              GREATEST((SELECT COALESCE(max(id),1) FROM public.empresas), 1));

SELECT public.linkai_ensure_escritorio(id) FROM public.empresas;

UPDATE public.usuarios SET is_platform_superadmin = true
 WHERE upper(COALESCE(permissao,'')) IN ('SUPERADMIN','SUPERADMINISTRADOR');

UPDATE public.usuarios SET empresa_id = 1
 WHERE empresa_id IS NULL AND lower(email) LIKE '%@2lock.com.br';
UPDATE public.usuarios SET empresa_id = 2 WHERE empresa_id IS NULL;

-- Atribuição inicial no ESCRITORIO preservando o acesso atual
INSERT INTO public.linkai_usuario_obras (usuario_id, obra_id, perfil_codigo, principal, ativo)
SELECT u.id,
       o.id,
       CASE
         WHEN upper(COALESCE(u.permissao,'')) IN ('ADMIN','ADMINISTRADOR') THEN 'supervisor_empresa'
         WHEN upper(COALESCE(u.permissao,'')) = 'OPERADOR' THEN 'fiscal_obra'
         ELSE 'consulta_obra'
       END,
       true, true
  FROM public.usuarios u
  JOIN public.linkai_obras o
    ON o.empresa_id = u.empresa_id AND o.tipo = 'escritorio' AND o.ativo
 WHERE NOT u.is_platform_superadmin
   AND NOT EXISTS (SELECT 1 FROM public.linkai_usuario_obras uo
                    WHERE uo.usuario_id = u.id AND uo.ativo);

-- Histórico antigo fica no ESCRITORIO da empresa correspondente
UPDATE public.lumina_queue_requests r
   SET obra_id = public.linkai_ensure_escritorio(COALESCE(r.empresa_id, 1))
 WHERE r.obra_id IS NULL;
UPDATE public.lumina_jobs j
   SET obra_id = public.linkai_ensure_escritorio(COALESCE(j.empresa_id, 1))
 WHERE j.obra_id IS NULL;
UPDATE public.lumina_queue_logs l
   SET obra_id = public.linkai_ensure_escritorio(COALESCE(l.empresa_id, 1))
 WHERE l.obra_id IS NULL;
UPDATE public.pedidos_pendentes SET empresa_id = 2, obra_id = public.linkai_ensure_escritorio(2)
 WHERE obra_id IS NULL;
UPDATE public.notas_processadas SET empresa_id = 2, obra_id = public.linkai_ensure_escritorio(2)
 WHERE obra_id IS NULL;
UPDATE public.robot_logs SET empresa_id = 2, obra_id = public.linkai_ensure_escritorio(2)
 WHERE obra_id IS NULL;

-- ============================================ claims internos no token
CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  v_claims jsonb;
  v_usuario record;
  v_perfil text := 'sem_acesso';
BEGIN
  v_claims := COALESCE(event -> 'claims', '{}'::jsonb);

  SELECT u.id, u.empresa_id, u.ariia_user_id, u.ativo, u.is_platform_superadmin
    INTO v_usuario
  FROM public.usuarios u
  WHERE u.auth_user_id = (event ->> 'user_id')::uuid;

  IF FOUND THEN
    IF COALESCE(v_usuario.is_platform_superadmin, false) THEN
      v_perfil := 'superadmin_2lock';
    ELSE
      SELECT COALESCE((
        SELECT uo.perfil_codigo FROM public.linkai_usuario_obras uo
         WHERE uo.usuario_id = v_usuario.id AND uo.ativo
         ORDER BY uo.principal DESC, uo.created_at LIMIT 1), 'sem_acesso')
        INTO v_perfil;
    END IF;

    v_claims := jsonb_set(v_claims, '{empresa_id}', COALESCE(to_jsonb(v_usuario.empresa_id), 'null'::jsonb), true);
    v_claims := jsonb_set(v_claims, '{ariia_user_id}', COALESCE(to_jsonb(v_usuario.ariia_user_id), 'null'::jsonb), true);
    v_claims := jsonb_set(v_claims, '{usuario_id}', to_jsonb(v_usuario.id), true);
    v_claims := jsonb_set(v_claims, '{ativo}', to_jsonb(COALESCE(v_usuario.ativo, false)), true);
    v_claims := jsonb_set(v_claims, '{is_platform_superadmin}',
      to_jsonb(COALESCE(v_usuario.is_platform_superadmin, false)), true);
  ELSE
    v_claims := jsonb_set(v_claims, '{empresa_id}', 'null'::jsonb, true);
    v_claims := jsonb_set(v_claims, '{ariia_user_id}', 'null'::jsonb, true);
    v_claims := jsonb_set(v_claims, '{usuario_id}', 'null'::jsonb, true);
    v_claims := jsonb_set(v_claims, '{ativo}', 'false'::jsonb, true);
    v_claims := jsonb_set(v_claims, '{is_platform_superadmin}', 'false'::jsonb, true);
  END IF;

  v_claims := jsonb_set(v_claims, '{perfil_interno}', to_jsonb(v_perfil), true);
  v_claims := jsonb_set(v_claims, '{permissao}', to_jsonb(v_perfil), true);

  RETURN jsonb_set(event, '{claims}', v_claims, true);
END;
$$;

-- ============================================= fila do Lumina com obra
CREATE OR REPLACE FUNCTION public.enqueue_lumina_request(
  p_action text DEFAULT 'launch_notes',
  p_payload jsonb DEFAULT '{}'::jsonb,
  p_items jsonb DEFAULT '[]'::jsonb
)
RETURNS public.lumina_queue_requests
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  v_user uuid := auth.uid();
  v_usuario_id integer := public.linkai_current_usuario_id();
  v_empresa integer := public.linkai_current_empresa_id();
  v_obra uuid := public.linkai_obra_principal(v_usuario_id);
  v_items jsonb := COALESCE(p_items, '[]'::jsonb);
  v_count integer;
  v_request public.lumina_queue_requests;
BEGIN
  IF v_user IS NULL OR v_usuario_id IS NULL THEN
    RAISE EXCEPTION 'Usuário não autenticado ou inativo.' USING ERRCODE = '42501';
  END IF;

  IF NOT public.linkai_has_permissao('notes.launch') THEN
    RAISE EXCEPTION 'Permissão insuficiente para lançar notas.' USING ERRCODE = '42501';
  END IF;

  IF COALESCE(p_action, 'launch_notes') <> 'launch_notes' THEN
    RAISE EXCEPTION 'Ação inválida para a fila do Lumina: %', p_action;
  END IF;

  IF jsonb_typeof(v_items) <> 'array' THEN
    RAISE EXCEPTION 'A lista de itens deve ser um array JSON.';
  END IF;

  IF jsonb_array_length(v_items) = 0 THEN
    v_items := jsonb_build_array(COALESCE(p_payload, '{}'::jsonb));
  END IF;

  v_count := jsonb_array_length(v_items);
  IF v_count > 1000 THEN
    RAISE EXCEPTION 'A solicitação excede o limite de 1000 itens.';
  END IF;

  INSERT INTO public.lumina_queue_requests (
    requested_by, empresa_id, obra_id, action, status, total_items, message
  ) VALUES (
    v_user, v_empresa, v_obra, 'launch_notes', 'queued', v_count,
    'Solicitação registrada na fila. Aguardando uma máquina disponível.'
  ) RETURNING * INTO v_request;

  INSERT INTO public.lumina_jobs (
    requested_by, empresa_id, obra_id, action, status, payload, message, queue_request_id, item_number
  )
  SELECT
    v_user, v_empresa, v_obra, 'launch_notes', 'queued',
    CASE WHEN jsonb_typeof(item.value) = 'object' THEN item.value ELSE jsonb_build_object('value', item.value) END,
    'Solicitação registrada na fila. Aguardando uma máquina disponível.',
    v_request.id, item.ordinality::int
  FROM jsonb_array_elements(v_items) WITH ORDINALITY AS item(value, ordinality);

  PERFORM public.linkai_log_activity(
    'notes.launch.enqueued', 'started',
    jsonb_build_object('total_items', v_count, 'queue_number', v_request.queue_number),
    'Solicitação de lançamento de notas registrada na fila.', v_obra);

  RETURN v_request;
END;
$$;

-- propaga obra_id do job para o log de arquivamento
CREATE OR REPLACE FUNCTION public.lumina_archive_job(p_job_id uuid, p_status text, p_message text)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  v_job public.lumina_jobs;
  v_number bigint;
  v_request uuid;
BEGIN
  SELECT * INTO v_job FROM public.lumina_jobs WHERE id = p_job_id FOR UPDATE;
  IF NOT FOUND THEN RETURN false; END IF;

  SELECT queue_number INTO v_number
  FROM public.lumina_queue_requests WHERE id = v_job.queue_request_id;

  INSERT INTO public.lumina_queue_logs (
    queue_request_id, queue_item_id, queue_number, item_number, requested_by, empresa_id, obra_id,
    action, status, payload, worker_id, attempts, queued_at, started_at, finished_at, message
  ) VALUES (
    v_job.queue_request_id, v_job.id, COALESCE(v_number, 0), COALESCE(v_job.item_number, 1),
    v_job.requested_by, v_job.empresa_id, v_job.obra_id, v_job.action, p_status,
    COALESCE(v_job.payload, '{}'::jsonb),
    v_job.worker_id, v_job.attempts, v_job.created_at, v_job.started_at, now(), p_message
  );

  v_request := v_job.queue_request_id;
  DELETE FROM public.lumina_jobs WHERE id = v_job.id;
  PERFORM public.lumina_refresh_request(v_request);
  RETURN true;
END;
$$;

-- =========================================================== GRANTS / RLS
GRANT SELECT ON public.linkai_perfis_internos TO authenticated;
GRANT SELECT ON public.linkai_permissoes TO authenticated;
GRANT SELECT ON public.linkai_perfil_permissoes TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.linkai_obras TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.linkai_usuario_obras TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.linkai_user_convites TO authenticated;
GRANT SELECT, INSERT ON public.linkai_activity_logs TO authenticated;
GRANT SELECT ON public.pedidos_pendentes TO authenticated;
GRANT SELECT ON public.notas_processadas TO authenticated;
GRANT SELECT ON public.robot_logs TO authenticated;
GRANT ALL ON public.linkai_perfis_internos TO service_role;
GRANT ALL ON public.linkai_permissoes TO service_role;
GRANT ALL ON public.linkai_perfil_permissoes TO service_role;
GRANT ALL ON public.linkai_obras TO service_role;
GRANT ALL ON public.linkai_usuario_obras TO service_role;
GRANT ALL ON public.linkai_user_convites TO service_role;
GRANT ALL ON public.linkai_activity_logs TO service_role;

ALTER TABLE public.linkai_perfis_internos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.linkai_permissoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.linkai_perfil_permissoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.linkai_obras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.linkai_usuario_obras ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.linkai_user_convites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.linkai_activity_logs ENABLE ROW LEVEL SECURITY;

-- catálogos: leitura para autenticados, escrita apenas service_role
DROP POLICY IF EXISTS linkai_perfis_read ON public.linkai_perfis_internos;
CREATE POLICY linkai_perfis_read ON public.linkai_perfis_internos FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS linkai_perfis_service ON public.linkai_perfis_internos;
CREATE POLICY linkai_perfis_service ON public.linkai_perfis_internos FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS linkai_permissoes_read ON public.linkai_permissoes;
CREATE POLICY linkai_permissoes_read ON public.linkai_permissoes FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS linkai_permissoes_service ON public.linkai_permissoes;
CREATE POLICY linkai_permissoes_service ON public.linkai_permissoes FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS linkai_perfil_permissoes_read ON public.linkai_perfil_permissoes;
CREATE POLICY linkai_perfil_permissoes_read ON public.linkai_perfil_permissoes FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS linkai_perfil_permissoes_service ON public.linkai_perfil_permissoes;
CREATE POLICY linkai_perfil_permissoes_service ON public.linkai_perfil_permissoes FOR ALL TO service_role USING (true) WITH CHECK (true);

-- obras
DROP POLICY IF EXISTS linkai_obras_select ON public.linkai_obras;
CREATE POLICY linkai_obras_select ON public.linkai_obras FOR SELECT TO authenticated
USING (id IN (SELECT public.linkai_obras_visiveis()));

DROP POLICY IF EXISTS linkai_obras_insert ON public.linkai_obras;
CREATE POLICY linkai_obras_insert ON public.linkai_obras FOR INSERT TO authenticated
WITH CHECK (public.linkai_is_platform_superadmin()
  OR (public.linkai_has_permissao('works.manage') AND empresa_id = public.linkai_current_empresa_id()));

DROP POLICY IF EXISTS linkai_obras_update ON public.linkai_obras;
CREATE POLICY linkai_obras_update ON public.linkai_obras FOR UPDATE TO authenticated
USING (public.linkai_is_platform_superadmin()
  OR (public.linkai_has_permissao('works.manage') AND empresa_id = public.linkai_current_empresa_id()))
WITH CHECK (public.linkai_is_platform_superadmin()
  OR (public.linkai_has_permissao('works.manage') AND empresa_id = public.linkai_current_empresa_id()));

DROP POLICY IF EXISTS linkai_obras_service ON public.linkai_obras;
CREATE POLICY linkai_obras_service ON public.linkai_obras FOR ALL TO service_role USING (true) WITH CHECK (true);

-- atribuições
DROP POLICY IF EXISTS linkai_usuario_obras_select ON public.linkai_usuario_obras;
CREATE POLICY linkai_usuario_obras_select ON public.linkai_usuario_obras FOR SELECT TO authenticated
USING (usuario_id = public.linkai_current_usuario_id()
   OR obra_id IN (SELECT public.linkai_obras_visiveis()));

DROP POLICY IF EXISTS linkai_usuario_obras_write ON public.linkai_usuario_obras;
CREATE POLICY linkai_usuario_obras_write ON public.linkai_usuario_obras FOR INSERT TO authenticated
WITH CHECK (public.linkai_can_manage_empresa(
  (SELECT o.empresa_id FROM public.linkai_obras o WHERE o.id = obra_id)));

DROP POLICY IF EXISTS linkai_usuario_obras_update ON public.linkai_usuario_obras;
CREATE POLICY linkai_usuario_obras_update ON public.linkai_usuario_obras FOR UPDATE TO authenticated
USING (public.linkai_can_manage_empresa(
  (SELECT o.empresa_id FROM public.linkai_obras o WHERE o.id = obra_id)))
WITH CHECK (public.linkai_can_manage_empresa(
  (SELECT o.empresa_id FROM public.linkai_obras o WHERE o.id = obra_id)));

DROP POLICY IF EXISTS linkai_usuario_obras_service ON public.linkai_usuario_obras;
CREATE POLICY linkai_usuario_obras_service ON public.linkai_usuario_obras FOR ALL TO service_role USING (true) WITH CHECK (true);

-- convites
DROP POLICY IF EXISTS linkai_convites_select ON public.linkai_user_convites;
CREATE POLICY linkai_convites_select ON public.linkai_user_convites FOR SELECT TO authenticated
USING (public.linkai_can_manage_empresa(empresa_id));

DROP POLICY IF EXISTS linkai_convites_insert ON public.linkai_user_convites;
CREATE POLICY linkai_convites_insert ON public.linkai_user_convites FOR INSERT TO authenticated
WITH CHECK (public.linkai_can_manage_empresa(empresa_id));

DROP POLICY IF EXISTS linkai_convites_update ON public.linkai_user_convites;
CREATE POLICY linkai_convites_update ON public.linkai_user_convites FOR UPDATE TO authenticated
USING (public.linkai_can_manage_empresa(empresa_id))
WITH CHECK (public.linkai_can_manage_empresa(empresa_id));

DROP POLICY IF EXISTS linkai_convites_service ON public.linkai_user_convites;
CREATE POLICY linkai_convites_service ON public.linkai_user_convites FOR ALL TO service_role USING (true) WITH CHECK (true);

-- logs de atividade
DROP POLICY IF EXISTS linkai_activity_select ON public.linkai_activity_logs;
CREATE POLICY linkai_activity_select ON public.linkai_activity_logs FOR SELECT TO authenticated
USING (actor_user_id = auth.uid()
   OR actor_usuario_id = public.linkai_current_usuario_id()
   OR public.linkai_is_platform_superadmin()
   OR (public.linkai_has_permissao('access.manage') AND empresa_id = public.linkai_current_empresa_id())
   OR (public.linkai_has_permissao('logs.view') AND obra_id IN (SELECT public.linkai_obras_visiveis())));

DROP POLICY IF EXISTS linkai_activity_insert ON public.linkai_activity_logs;
CREATE POLICY linkai_activity_insert ON public.linkai_activity_logs FOR INSERT TO authenticated
WITH CHECK (actor_user_id = auth.uid());

DROP POLICY IF EXISTS linkai_activity_service ON public.linkai_activity_logs;
CREATE POLICY linkai_activity_service ON public.linkai_activity_logs FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ---------------------------- usuarios: acessos administrativos internos
DROP POLICY IF EXISTS usuarios_admin_delete ON public.usuarios;
DROP POLICY IF EXISTS usuarios_admin_update ON public.usuarios;
DROP POLICY IF EXISTS usuarios_admin_write ON public.usuarios;
DROP POLICY IF EXISTS usuarios_select_self_or_empresa ON public.usuarios;

CREATE POLICY usuarios_select_self_or_empresa ON public.usuarios FOR SELECT TO authenticated
USING (auth_user_id = auth.uid()
   OR public.linkai_is_platform_superadmin()
   OR (empresa_id IS NOT NULL AND empresa_id = public.linkai_current_empresa_id()));

CREATE POLICY usuarios_admin_write ON public.usuarios FOR INSERT TO authenticated
WITH CHECK (public.linkai_can_manage_empresa(empresa_id));

CREATE POLICY usuarios_admin_update ON public.usuarios FOR UPDATE TO authenticated
USING (public.linkai_can_manage_empresa(empresa_id))
WITH CHECK (public.linkai_can_manage_empresa(empresa_id));

CREATE POLICY usuarios_admin_delete ON public.usuarios FOR DELETE TO authenticated
USING (public.linkai_can_manage_empresa(empresa_id));

-- empresas
DROP POLICY IF EXISTS empresas_select_own ON public.empresas;
CREATE POLICY empresas_select_own ON public.empresas FOR SELECT TO authenticated
USING (public.linkai_is_platform_superadmin() OR id = public.linkai_current_empresa_id());

-- ----------------------------------- dados operacionais escopados por obra
DROP POLICY IF EXISTS pedidos_obra_select ON public.pedidos_pendentes;
CREATE POLICY pedidos_obra_select ON public.pedidos_pendentes FOR SELECT TO authenticated
USING (public.linkai_can_access_obra(obra_id));

DROP POLICY IF EXISTS notas_obra_select ON public.notas_processadas;
CREATE POLICY notas_obra_select ON public.notas_processadas FOR SELECT TO authenticated
USING (public.linkai_can_access_obra(obra_id));

DROP POLICY IF EXISTS robot_logs_obra_select ON public.robot_logs;
CREATE POLICY robot_logs_obra_select ON public.robot_logs FOR SELECT TO authenticated
USING (public.linkai_can_access_obra(obra_id) AND public.linkai_has_permissao('logs.view'));

-- ------------------------------------------------ fila do Lumina por obra
DROP POLICY IF EXISTS lumina_jobs_select ON public.lumina_jobs;
CREATE POLICY lumina_jobs_select ON public.lumina_jobs FOR SELECT TO authenticated
USING (requested_by = auth.uid()
   OR public.linkai_is_platform_superadmin()
   OR (public.linkai_has_permissao('queue.monitor') AND obra_id IN (SELECT public.linkai_obras_visiveis())));

DROP POLICY IF EXISTS lumina_queue_requests_select ON public.lumina_queue_requests;
CREATE POLICY lumina_queue_requests_select ON public.lumina_queue_requests FOR SELECT TO authenticated
USING (requested_by = auth.uid()
   OR public.linkai_is_platform_superadmin()
   OR (public.linkai_has_permissao('queue.monitor') AND obra_id IN (SELECT public.linkai_obras_visiveis())));

DROP POLICY IF EXISTS lumina_queue_logs_select ON public.lumina_queue_logs;
CREATE POLICY lumina_queue_logs_select ON public.lumina_queue_logs FOR SELECT TO authenticated
USING (requested_by = auth.uid()
   OR public.linkai_is_platform_superadmin()
   OR (public.linkai_has_permissao('queue.monitor') AND obra_id IN (SELECT public.linkai_obras_visiveis())));

-- anon não acessa nada disso
REVOKE ALL ON public.linkai_perfis_internos, public.linkai_permissoes, public.linkai_perfil_permissoes,
              public.linkai_obras, public.linkai_usuario_obras, public.linkai_user_convites,
              public.linkai_activity_logs FROM anon;
REVOKE ALL ON public.pedidos_pendentes, public.notas_processadas, public.robot_logs,
              public.regras_imposto FROM anon;