-- =========================================================
-- 1. usuarios: chave canônica do Ariia + id automático
-- =========================================================

ALTER TABLE public.usuarios
  ADD COLUMN IF NOT EXISTS ariia_user_id text,
  ADD COLUMN IF NOT EXISTS avatar_url text;

-- id passa a ser gerado automaticamente (hoje é integer NOT NULL sem default,
-- o que impediria o provisionamento automático do usuário-espelho).
DO $$
DECLARE
  v_max bigint;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_attribute
    WHERE attrelid = 'public.usuarios'::regclass
      AND attname = 'id'
      AND attidentity IN ('a', 'd')
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'usuarios'
      AND column_name = 'id' AND column_default IS NOT NULL
  ) THEN
    ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    SELECT COALESCE(MAX(id), 0) INTO v_max FROM public.usuarios;
    PERFORM setval(pg_get_serial_sequence('public.usuarios', 'id'), v_max + 1, false);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_ariia_user_id_key
  ON public.usuarios (ariia_user_id) WHERE ariia_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS usuarios_auth_user_id_key
  ON public.usuarios (auth_user_id);

CREATE INDEX IF NOT EXISTS usuarios_empresa_id_idx
  ON public.usuarios (empresa_id);

-- Vincula o registro de negócio ao usuário-espelho do Supabase Auth.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'usuarios_auth_user_id_fkey'
  ) THEN
    ALTER TABLE public.usuarios
      ADD CONSTRAINT usuarios_auth_user_id_fkey
      FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'usuarios_empresa_id_fkey'
  ) THEN
    ALTER TABLE public.usuarios
      ADD CONSTRAINT usuarios_empresa_id_fkey
      FOREIGN KEY (empresa_id) REFERENCES public.empresas(id) ON DELETE SET NULL;
  END IF;
END $$;

-- =========================================================
-- 2. Custom Access Token Hook
--    Injeta empresa_id, permissao e ariia_user_id no JWT a cada emissão,
--    lendo direto de public.usuarios. Sem app_metadata, sem JOIN nas policies.
-- =========================================================

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_claims  jsonb;
  v_usuario record;
BEGIN
  v_claims := COALESCE(event -> 'claims', '{}'::jsonb);

  SELECT u.empresa_id, u.permissao, u.ariia_user_id, u.ativo, u.id
    INTO v_usuario
  FROM public.usuarios u
  WHERE u.auth_user_id = (event ->> 'user_id')::uuid;

  IF FOUND THEN
    v_claims := jsonb_set(v_claims, '{empresa_id}',
      COALESCE(to_jsonb(v_usuario.empresa_id), 'null'::jsonb), true);
    v_claims := jsonb_set(v_claims, '{permissao}',
      COALESCE(to_jsonb(v_usuario.permissao), 'null'::jsonb), true);
    v_claims := jsonb_set(v_claims, '{ariia_user_id}',
      COALESCE(to_jsonb(v_usuario.ariia_user_id), 'null'::jsonb), true);
    v_claims := jsonb_set(v_claims, '{usuario_id}',
      to_jsonb(v_usuario.id), true);
    v_claims := jsonb_set(v_claims, '{ativo}',
      to_jsonb(COALESCE(v_usuario.ativo, false)), true);
  ELSE
    v_claims := jsonb_set(v_claims, '{empresa_id}',    'null'::jsonb, true);
    v_claims := jsonb_set(v_claims, '{permissao}',     'null'::jsonb, true);
    v_claims := jsonb_set(v_claims, '{ariia_user_id}', 'null'::jsonb, true);
    v_claims := jsonb_set(v_claims, '{usuario_id}',    'null'::jsonb, true);
    v_claims := jsonb_set(v_claims, '{ativo}',         'false'::jsonb, true);
  END IF;

  RETURN jsonb_set(event, '{claims}', v_claims, true);
END;
$$;

GRANT USAGE ON SCHEMA public TO supabase_auth_admin;
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook(jsonb) TO supabase_auth_admin;
REVOKE EXECUTE ON FUNCTION public.custom_access_token_hook(jsonb) FROM authenticated, anon, public;
GRANT SELECT ON public.usuarios TO supabase_auth_admin;

-- O hook roda como supabase_auth_admin e precisa ler usuarios apesar da RLS.
DROP POLICY IF EXISTS auth_admin_read_usuarios ON public.usuarios;
CREATE POLICY auth_admin_read_usuarios ON public.usuarios
  FOR SELECT TO supabase_auth_admin USING (true);

-- =========================================================
-- 3. Helpers que leem as claims do JWT (sem tocar no banco)
-- =========================================================

CREATE OR REPLACE FUNCTION public.jwt_empresa_id()
RETURNS integer LANGUAGE sql STABLE SET search_path = public AS $$
  SELECT NULLIF(auth.jwt() ->> 'empresa_id', '')::integer
$$;

CREATE OR REPLACE FUNCTION public.jwt_permissao()
RETURNS text LANGUAGE sql STABLE SET search_path = public AS $$
  SELECT NULLIF(auth.jwt() ->> 'permissao', '')
$$;

CREATE OR REPLACE FUNCTION public.jwt_ariia_user_id()
RETURNS text LANGUAGE sql STABLE SET search_path = public AS $$
  SELECT NULLIF(auth.jwt() ->> 'ariia_user_id', '')
$$;

CREATE OR REPLACE FUNCTION public.jwt_ativo()
RETURNS boolean LANGUAGE sql STABLE SET search_path = public AS $$
  SELECT COALESCE((auth.jwt() ->> 'ativo')::boolean, false)
$$;

CREATE OR REPLACE FUNCTION public.jwt_has_permissao(_permissoes text[])
RETURNS boolean LANGUAGE sql STABLE SET search_path = public AS $$
  SELECT public.jwt_ativo() AND public.jwt_permissao() = ANY (_permissoes)
$$;

GRANT EXECUTE ON FUNCTION public.jwt_empresa_id()                 TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.jwt_permissao()                  TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.jwt_ariia_user_id()              TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.jwt_ativo()                      TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.jwt_has_permissao(text[])        TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_usuario_atual()              TO authenticated, service_role;

-- =========================================================
-- 4. GRANTs + RLS: empresas
-- =========================================================

ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;
GRANT SELECT ON public.empresas TO authenticated;
GRANT ALL    ON public.empresas TO service_role;

DROP POLICY IF EXISTS service_role_all_empresas ON public.empresas;
CREATE POLICY service_role_all_empresas ON public.empresas
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS empresas_select_own ON public.empresas;
CREATE POLICY empresas_select_own ON public.empresas
  FOR SELECT TO authenticated
  USING (public.jwt_ativo() AND id = public.jwt_empresa_id());

-- =========================================================
-- 5. GRANTs + RLS: usuarios
-- =========================================================

ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.usuarios TO authenticated;
GRANT ALL ON public.usuarios TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

DROP POLICY IF EXISTS service_role_all_usuarios ON public.usuarios;
CREATE POLICY service_role_all_usuarios ON public.usuarios
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS usuarios_select_self_or_empresa ON public.usuarios;
CREATE POLICY usuarios_select_self_or_empresa ON public.usuarios
  FOR SELECT TO authenticated
  USING (
    auth_user_id = auth.uid()
    OR (
      public.jwt_ativo()
      AND empresa_id IS NOT NULL
      AND empresa_id = public.jwt_empresa_id()
    )
  );

DROP POLICY IF EXISTS usuarios_admin_write ON public.usuarios;
CREATE POLICY usuarios_admin_write ON public.usuarios
  FOR INSERT TO authenticated
  WITH CHECK (
    public.jwt_has_permissao(ARRAY['admin'])
    AND empresa_id = public.jwt_empresa_id()
  );

DROP POLICY IF EXISTS usuarios_admin_update ON public.usuarios;
CREATE POLICY usuarios_admin_update ON public.usuarios
  FOR UPDATE TO authenticated
  USING (public.jwt_has_permissao(ARRAY['admin']) AND empresa_id = public.jwt_empresa_id())
  WITH CHECK (public.jwt_has_permissao(ARRAY['admin']) AND empresa_id = public.jwt_empresa_id());

DROP POLICY IF EXISTS usuarios_admin_delete ON public.usuarios;
CREATE POLICY usuarios_admin_delete ON public.usuarios
  FOR DELETE TO authenticated
  USING (public.jwt_has_permissao(ARRAY['admin']) AND empresa_id = public.jwt_empresa_id());

-- =========================================================
-- 6. GRANTs + RLS: tabelas de negócio
--    Ainda não possuem empresa_id; leitura para autenticados ativos,
--    escrita para admin/operador. Restringir por empresa quando a coluna existir.
-- =========================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON public.pedidos_pendentes  TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notas_processadas  TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.regras_imposto     TO authenticated;
GRANT SELECT                         ON public.robot_logs         TO authenticated;
GRANT ALL ON public.pedidos_pendentes TO service_role;
GRANT ALL ON public.notas_processadas TO service_role;
GRANT ALL ON public.regras_imposto    TO service_role;
GRANT ALL ON public.robot_logs        TO service_role;

DROP POLICY IF EXISTS pedidos_select_authenticated ON public.pedidos_pendentes;
CREATE POLICY pedidos_select_authenticated ON public.pedidos_pendentes
  FOR SELECT TO authenticated USING (public.jwt_ativo());

DROP POLICY IF EXISTS pedidos_write_operador ON public.pedidos_pendentes;
CREATE POLICY pedidos_write_operador ON public.pedidos_pendentes
  FOR ALL TO authenticated
  USING (public.jwt_has_permissao(ARRAY['admin','operador']))
  WITH CHECK (public.jwt_has_permissao(ARRAY['admin','operador']));

DROP POLICY IF EXISTS notas_select_authenticated ON public.notas_processadas;
CREATE POLICY notas_select_authenticated ON public.notas_processadas
  FOR SELECT TO authenticated USING (public.jwt_ativo());

DROP POLICY IF EXISTS notas_write_operador ON public.notas_processadas;
CREATE POLICY notas_write_operador ON public.notas_processadas
  FOR ALL TO authenticated
  USING (public.jwt_has_permissao(ARRAY['admin','operador']))
  WITH CHECK (public.jwt_has_permissao(ARRAY['admin','operador']));

DROP POLICY IF EXISTS regras_select_authenticated ON public.regras_imposto;
CREATE POLICY regras_select_authenticated ON public.regras_imposto
  FOR SELECT TO authenticated USING (public.jwt_ativo());

DROP POLICY IF EXISTS regras_write_admin ON public.regras_imposto;
CREATE POLICY regras_write_admin ON public.regras_imposto
  FOR ALL TO authenticated
  USING (public.jwt_has_permissao(ARRAY['admin']))
  WITH CHECK (public.jwt_has_permissao(ARRAY['admin']));

DROP POLICY IF EXISTS logs_select_authenticated ON public.robot_logs;
CREATE POLICY logs_select_authenticated ON public.robot_logs
  FOR SELECT TO authenticated USING (public.jwt_has_permissao(ARRAY['admin','operador']));
